# -*- coding: utf-8 -*-
"""
Django settings for aocops project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""
#-*- codig:utf-8 -*-
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from django.conf import global_settings


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'qb8_oqnjx-egq#_27x3ufv6=_ygp%vk**#+@gid&jg58)no4n2'

#DAB_FIELD_RENDERER ='django_admin_bootstrapped.renderers.BootstrapFieldRenderer'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['c.ops.com']

FILE_CHARSET= 'utf-8' 
DEFAULT_CHARSET='utf-8'
# Application definition



INSTALLED_APPS = (
    #'django_admin_bootstrapped', #后台使用bootstrap样式
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'login',
    'vminfo',
    'vmset',
    'index',
    'devtest',
    'idcinfo',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'aocops.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates/'),],
        #'DIRS': [],
        #'APP_DIRS': False,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                ##定义视图全局变量
                'index.views.glob'
            ],
        },
    },
]

WSGI_APPLICATION = 'aocops.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#    }
#}
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'aoc',
        'USER': 'aoc',
        'PASSWORD': 'aoc',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}



# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

#LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
#STATIC_URL = '/static/'

#STATIC_ROOT = os.path.join(BASE_DIR, 'collected_static')
##项目根目录下面的static,非debug模式不适用，
STATICFILES_DIRS = (
        os.path.join(BASE_DIR, 'static/'),
        )

STATIC_URL = '/static/'

MEDIA_ROOT = os.path.abspath('upload/')
MEDIA_URL = '/upload/'
